name: Languages (mono)
on:
  schedule: [{ cron: "0 6 * * *" }]
  workflow_dispatch:

jobs:
  langs:
    runs-on: ubuntu-latest
    steps:
      - name: Top Langs · LIGHT
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: langs-mono-light.svg
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 8
          config_display: regular
          extras_css: |
            * { 
              font-family: 'SF Mono', 'Monaco', 'Inconsolata', 'Fira Code', 'Droid Sans Mono', 'Source Code Pro', monospace !important;
            }
            h2 { 
              color: #4A5568 !important; 
              font-size: 11px !important;
              font-weight: 500 !important;
              text-transform: uppercase !important;
              letter-spacing: 1.5px !important;
            }
            .field { 
              font-size: 11px !important;
              font-weight: 400 !important;
            }
            svg {
              background: transparent !important;
            }
          # same mid-gray for every bar (monochrome, not pure black)
          plugin_languages_colors: >
            0:#6B7280, 1:#6B7280, 2:#6B7280, 3:#6B7280,
            4:#6B7280, 5:#6B7280, 6:#6B7280, 7:#6B7280

      - name: Top Langs · DARK
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: langs-mono-dark.svg
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 8
          config_display: regular
          extras_css: |
            * { 
              font-family: 'SF Mono', 'Monaco', 'Inconsolata', 'Fira Code', 'Droid Sans Mono', 'Source Code Pro', monospace !important;
            }
            h2 { 
              color: #A0AEC0 !important; 
              font-size: 11px !important;
              font-weight: 500 !important;
              text-transform: uppercase !important;
              letter-spacing: 1.5px !important;
            }
            .field { 
              font-size: 11px !important;
              font-weight: 400 !important;
            }
            svg {
              background: transparent !important;
            }
          # light gray for dark backgrounds
          plugin_languages_colors: >
            0:#D1D5DB, 1:#D1D5DB, 2:#D1D5DB, 3:#D1D5DB,
            4:#D1D5DB, 5:#D1D5DB, 6:#D1D5DB, 7:#D1D5DB

